/**
 * Scale definitions and related functions
 */

// Define all scales from the document
export const scaleDefinitions = [
  // Family 1
  {
    family: 1,
    name: "Major (Ionian)",
    intervals: "1-1-½-1-1-1-½",
    systematicName: "Ionian",
    chords: "Ma7",
    steps: [0, 2, 4, 5, 7, 9, 11],
  },
  {
    family: 1,
    name: "Dorian",
    intervals: "1-½-1-1-1-½-1",
    systematicName: "Dorian",
    chords: "mi7",
    steps: [0, 2, 3, 5, 7, 9, 10],
  },
  {
    family: 1,
    name: "Phrygian",
    intervals: "½-1-1-1-½-1-1",
    systematicName: "Phrygian",
    chords: "mi7",
    steps: [0, 1, 3, 5, 7, 8, 10],
  },
  {
    family: 1,
    name: "Lydian",
    intervals: "1-1-1-½-1-1-½",
    systematicName: "Lydian",
    chords: "Ma7",
    steps: [0, 2, 4, 6, 7, 9, 11],
  },
  {
    family: 1,
    name: "Mixolydian",
    intervals: "1-1-½-1-1-½-1",
    systematicName: "Mixolydian",
    chords: "7",
    steps: [0, 2, 4, 5, 7, 9, 10],
  },
  {
    family: 1,
    name: "Natural Minor (Aeolian)",
    intervals: "1-½-1-1-½-1-1",
    systematicName: "Aeolian",
    chords: "mi7",
    steps: [0, 2, 3, 5, 7, 8, 10],
  },
  {
    family: 1,
    name: "Locrian",
    intervals: "½-1-1-½-1-1-1",
    systematicName: "Locrian",
    chords: "mi7b5",
    steps: [0, 1, 3, 5, 6, 8, 10],
  },

  // Family 2
  {
    family: 2,
    name: "Altered (Super Locrian)",
    intervals: "½-1-½-1-1-1-1",
    systematicName: "Ionian #1",
    chords: "7alt / mi7b5",
    steps: [0, 1, 3, 4, 6, 8, 10],
  },
  {
    family: 2,
    name: "Ascending Melodic Minor",
    intervals: "1-½-1-1-1-1-½",
    systematicName: "Dorian #7",
    chords: "miMa7",
    steps: [0, 2, 3, 5, 7, 9, 11],
  },
  {
    family: 2,
    name: "Dorian b2",
    intervals: "½-1-1-1-1-½-1",
    systematicName: "Phrygian #6",
    chords: "mi7",
    steps: [0, 1, 3, 5, 7, 9, 10],
  },
  {
    family: 2,
    name: "Lydian Augmented",
    intervals: "1-1-1-1-½-1-½",
    systematicName: "Lydian #5",
    chords: "Ma7#5",
    steps: [0, 2, 4, 6, 8, 9, 11],
  },
  {
    family: 2,
    name: "Lydian Dominant",
    intervals: "1-1-1-½-1-½-1",
    systematicName: "Mixolydian #4",
    chords: "7",
    steps: [0, 2, 4, 6, 7, 9, 10],
  },
  {
    family: 2,
    name: "Aeolian Dominant",
    intervals: "1-1-½-1-½-1-1",
    systematicName: "Aeolian #3",
    chords: "7",
    steps: [0, 2, 4, 5, 7, 8, 10],
  },
  {
    family: 2,
    name: "Half Diminished",
    intervals: "1-½-1-½-1-1-1",
    systematicName: "Locrian #2",
    chords: "mi7b5",
    steps: [0, 2, 3, 5, 6, 8, 10],
  },

  // Family 3
  {
    family: 3,
    name: "Major #5 (Major Augmented)",
    intervals: "1-1-½-1½-½-1-½",
    systematicName: "Ionian #5",
    chords: "Ma7#5",
    steps: [0, 2, 4, 5, 8, 9, 11],
  },
  {
    family: 3,
    name: "Dorian #4",
    intervals: "1-½-1½-½-1-½-1",
    systematicName: "Dorian #4",
    chords: "mi7",
    steps: [0, 2, 3, 6, 7, 9, 10],
  },
  {
    family: 3,
    name: "Phrygian Dominant",
    intervals: "½-1½-½-1-½-1-1",
    systematicName: "Phrygian #3",
    chords: "7",
    steps: [0, 1, 4, 5, 7, 8, 10],
  },
  {
    family: 3,
    name: "Lydian #2",
    intervals: "1½-½-1-½-1-1-½",
    systematicName: "Lydian #2",
    chords: "Ma7",
    steps: [0, 3, 4, 6, 7, 9, 11],
  },
  {
    family: 3,
    name: "Altered Dominant bb7",
    intervals: "½-1-½-1-1-½-1½",
    systematicName: "Mixolydian #1",
    chords: "dim7",
    steps: [0, 1, 3, 4, 6, 7, 10],
  },
  {
    family: 3,
    name: "Harmonic Minor",
    intervals: "1-½-1-1-½-1½-½",
    systematicName: "Aeolian #7",
    chords: "miMa7",
    steps: [0, 2, 3, 5, 7, 8, 11],
  },
  {
    family: 3,
    name: "Locrian ♮6",
    intervals: "½-1-1-½-1½-½-1",
    systematicName: "Locrian #6",
    chords: "mi7b5",
    steps: [0, 1, 3, 5, 6, 9, 10],
  },

  // Family 4
  {
    family: 4,
    name: "Harmonic Major",
    intervals: "1-1-½-1-½-1½-½",
    systematicName: "Ionian b6",
    chords: "Ma7",
    steps: [0, 2, 4, 5, 7, 8, 11],
  },
  {
    family: 4,
    name: "Dorian b5",
    intervals: "1-½-1-½-1½-½-1",
    systematicName: "Dorian b5",
    chords: "mi7b5",
    steps: [0, 2, 3, 5, 6, 9, 10],
  },
  {
    family: 4,
    name: "Phrygian b4",
    intervals: "½-1-½-1½-½-1-1",
    systematicName: "Phrygian b4",
    chords: "mi7 / 7",
    steps: [0, 1, 3, 4, 7, 8, 10],
  },
  {
    family: 4,
    name: "Lydian b3",
    intervals: "1-½-1½-½-1-1-½",
    systematicName: "Lydian b3",
    chords: "miMa7",
    steps: [0, 2, 3, 6, 7, 9, 11],
  },
  {
    family: 4,
    name: "Mixolydian b2",
    intervals: "½-1½-½-1-1-½-1",
    systematicName: "Mixolydian b2",
    chords: "7",
    steps: [0, 1, 4, 5, 7, 9, 10],
  },
  {
    family: 4,
    name: "Lydian Augmented #2",
    intervals: "1½-½-1-1-½-1-½",
    systematicName: "Aeolian b1",
    chords: "Ma7#5 / dim7",
    steps: [0, 3, 4, 6, 8, 9, 11],
  },
  {
    family: 4,
    name: "Locrian bb7",
    intervals: "½-1-1-½-1-½-1½",
    systematicName: "Locrian b7",
    chords: "dim7",
    steps: [0, 1, 3, 5, 6, 8, 10],
  },

  // Family 5
  {
    family: 5,
    name: "Diminished",
    intervals: "1-½-1-½-1-½-1-½",
    systematicName: "Diminished",
    chords: "dim7",
    steps: [0, 2, 3, 5, 6, 8, 9, 11],
  },
  {
    family: 5,
    name: "Dominant Diminished",
    intervals: "½-1-½-1-½-1-½-1",
    systematicName: "Inverted Diminished",
    chords: "7",
    steps: [0, 1, 3, 4, 6, 7, 9, 10],
  },

  // Family 6
  {
    family: 6,
    name: "Whole Tone",
    intervals: "1-1-1-1-1-1",
    systematicName: "Whole Tone",
    chords: "7 #5/b5",
    steps: [0, 2, 4, 6, 8, 10],
  },

  // Family 7
  {
    family: 7,
    name: "Augmented",
    intervals: "1½-½-1½-½-1½-½",
    systematicName: "Augmented",
    chords: "Ma7",
    steps: [0, 3, 4, 7, 8, 11],
  },
  {
    family: 7,
    name: "Inverted Augmented",
    intervals: "½-1½-½-1½-½-1½",
    systematicName: "Inverted Augmented",
    chords: "6#5",
    steps: [0, 1, 4, 5, 8, 9],
  },

  // Family 8: Pentatonic Scales (great for jazz, funk, soul, reggae)
  {
    family: 8,
    name: "Major Pentatonic",
    intervals: "1-1-1½-1-1½",
    systematicName: "Major Pentatonic",
    chords: "Ma7, 6, add9",
    steps: [0, 2, 4, 7, 9],
  },
  {
    family: 8,
    name: "Minor Pentatonic",
    intervals: "1½-1-1-1½-1",
    systematicName: "Minor Pentatonic",
    chords: "mi7, mi6",
    steps: [0, 3, 5, 7, 10],
  },
  {
    family: 8,
    name: "Egyptian Pentatonic",
    intervals: "1-1½-1-1½-1",
    systematicName: "Suspended Pentatonic",
    chords: "sus4, 7sus4",
    steps: [0, 2, 5, 7, 10],
  },
  {
    family: 8,
    name: "Blues Major Pentatonic",
    intervals: "1-1½-½-1½-1",
    systematicName: "Major Blues",
    chords: "Ma7, 6, 9",
    steps: [0, 2, 5, 6, 9],
  },
  {
    family: 8,
    name: "Ritusen Pentatonic",
    intervals: "1-1-1½-1-1½",
    systematicName: "Ritusen",
    chords: "sus2, add9",
    steps: [0, 2, 4, 7, 9],
  },

  // Family 9: Blues Scales (essential for jazz, funk, soul)
  {
    family: 9,
    name: "Minor Blues",
    intervals: "1½-1-½-½-1½-1",
    systematicName: "Minor Blues",
    chords: "mi7, 7",
    steps: [0, 3, 5, 6, 7, 10],
  },
  {
    family: 9,
    name: "Major Blues",
    intervals: "1-½-½-1½-1-1½",
    systematicName: "Major Blues",
    chords: "Ma7, 6, 9",
    steps: [0, 2, 3, 4, 7, 9],
  },
  {
    family: 9,
    name: "Dominant Blues",
    intervals: "1-1-½-½-1½-1",
    systematicName: "Mixolydian Blues",
    chords: "7, 9, 13",
    steps: [0, 2, 4, 5, 6, 9],
  },

  // Family 10: World/Modal Scales (great for EDM, world fusion)
  {
    family: 10,
    name: "Hirajoshi",
    intervals: "1-½-1½-½-2",
    systematicName: "Japanese Hirajoshi",
    chords: "mi, miMa7",
    steps: [0, 2, 3, 7, 8],
  },
  {
    family: 10,
    name: "In-Sen",
    intervals: "½-2-½-2-1",
    systematicName: "Japanese In-Sen",
    chords: "mi7b5",
    steps: [0, 1, 5, 6, 10],
  },
  {
    family: 10,
    name: "Iwato",
    intervals: "½-2-½-2-1",
    systematicName: "Japanese Iwato",
    chords: "dim7",
    steps: [0, 1, 5, 6, 10],
  },
  {
    family: 10,
    name: "Spanish Phrygian",
    intervals: "½-1½-½-1-½-1-1",
    systematicName: "Phrygian Dominant",
    chords: "7, 7b9",
    steps: [0, 1, 4, 5, 7, 8, 10],
  },
  {
    family: 10,
    name: "Hungarian Minor",
    intervals: "1-½-1½-½-½-1½-½",
    systematicName: "Double Harmonic Minor",
    chords: "miMa7, 7b9",
    steps: [0, 2, 3, 6, 7, 8, 11],
  },
  {
    family: 10,
    name: "Arabian",
    intervals: "½-1½-½-½-1½-½-1",
    systematicName: "Double Harmonic Major",
    chords: "Ma7, 7b9",
    steps: [0, 1, 4, 5, 7, 8, 11],
  },

  // Family 11: Jazz/Fusion Scales (for advanced jazz and fusion)
  {
    family: 11,
    name: "Bebop Dominant",
    intervals: "1-1-½-1-1-½-½-½",
    systematicName: "Mixolydian Bebop",
    chords: "7, 9, 13",
    steps: [0, 2, 4, 5, 7, 9, 10, 11],
  },
  {
    family: 11,
    name: "Bebop Major",
    intervals: "1-1-½-1-½-½-1-½",
    systematicName: "Ionian Bebop",
    chords: "Ma7, 6, 9",
    steps: [0, 2, 4, 5, 7, 8, 9, 11],
  },
  {
    family: 11,
    name: "Bebop Minor",
    intervals: "1-½-1-1-½-½-1-½",
    systematicName: "Dorian Bebop",
    chords: "mi7, mi6",
    steps: [0, 2, 3, 5, 7, 8, 9, 11],
  },
  {
    family: 11,
    name: "Bebop Locrian",
    intervals: "½-1-1-½-1-½-½-1",
    systematicName: "Locrian Bebop",
    chords: "mi7b5",
    steps: [0, 1, 3, 5, 6, 8, 9, 10],
  },

  // Family 12: Funk & Soul Scales (essential for funk, soul, R&B)
  {
    family: 12,
    name: "Funk Minor",
    intervals: "1½-½-½-1-½-1-1",
    systematicName: "Funk Dorian",
    chords: "mi7, 9, 13",
    steps: [0, 3, 4, 5, 7, 8, 10],
  },
  {
    family: 12,
    name: "Gospel Pentatonic",
    intervals: "1-1-1½-½-2",
    systematicName: "Gospel",
    chords: "Ma7, 9, 13",
    steps: [0, 2, 4, 7, 8],
  },
  {
    family: 12,
    name: "Mixo-Dorian",
    intervals: "1-½-1-1-1-½-1",
    systematicName: "Mixo-Dorian Hybrid",
    chords: "7, 9, 13",
    steps: [0, 2, 3, 5, 7, 9, 10],
  },

  // Family 13: Electronic & Modern Scales (for EDM and modern music)
  {
    family: 13,
    name: "Hexatonic",
    intervals: "1-1-1-1-1-1",
    systematicName: "Whole Tone",
    chords: "7#11, 7#5",
    steps: [0, 2, 4, 6, 8, 10],
  },
  {
    family: 13,
    name: "Prometheus",
    intervals: "1-1-1-1½-½-1",
    systematicName: "Prometheus",
    chords: "Ma7#11, 9",
    steps: [0, 2, 4, 6, 9, 10],
  },
  {
    family: 13,
    name: "Enigmatic",
    intervals: "½-1½-1-1-1-½-½",
    systematicName: "Enigmatic",
    chords: "Ma7b5",
    steps: [0, 1, 4, 6, 8, 10, 11],
  },
  {
    family: 13,
    name: "Ultralocrian",
    intervals: "½-1-½-1-½-1-1",
    systematicName: "Altered Dominant",
    chords: "7alt",
    steps: [0, 1, 3, 4, 6, 7, 9],
  },
];

export const familyChordTypes = {
  1: ["Ma7", "mi7", "7"],
  2: ["miMa7", "mi7b5", "7"],
  3: ["miMa7", "7", "dim7"],
  4: ["Ma7", "7", "mi7b5"],
  5: ["dim7", "mi7b5"],
  6: ["7", "Ma7#5"],
  7: ["Ma7#5", "6#5"],
  8: ["Ma7", "mi7", "add9", "sus4", "sus2"],
  9: ["mi7", "7", "9", "13"],
  10: ["mi7b5", "miMa7", "dim7"],
  11: ["Ma7", "mi7", "mi9", "9", "13", "7b9"],
  12: ["mi7", "9", "13", "6", "6/9"],
  13: ["Ma7#5", "7alt", "dim7"],
};
